version: '3.8'

networks:
  koompi-cloud-shared:
    external: true

services:
  # Docker Registry - Simplified and Stable
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      # Basic configuration
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      
      # Storage configuration
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      
      # Log level
      REGISTRY_LOG_LEVEL: "info"
      
      # Basic health check endpoint
      REGISTRY_HTTP_DEBUG_ADDR: 0.0.0.0:5001
      REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED: "false"
      
      # Disable complex maintenance for stability
      # We'll handle cleanup manually if needed
      
    volumes:
      # Using tmpfs for temporary storage (resets on restart)
      # Limited to 10GB
      - type: tmpfs
        target: /var/lib/registry
        tmpfs:
          size: 10737418240  # 10GB in bytes
      
    networks:
      - koompi-cloud-shared
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/v2/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s